### ISSUE TITLE
Can run on iOS. No podspec found for `react-native-smart-code`

### ISSUE THREAD

**Issue by rendomnet** [RoJoHub/react-native-smart-code#15]
I have this error.
[!] No podspec found for `react-native-smart-code` in `../node_modules/react-native-smart-code/ios`

**Comment by RoJoHub** [comment]
hello

thanks for u issues.

I have fixed this problem.

On version of **1.0.2**,please change to 
`pod 'RNCodeGenerator', path: '../node_modules/react-native-smart-code/ios/RNCodeGenerator.podspec'`

In next version.
I change the README.md
**1.0.4** is `pod 'react-native-smart-code', path: '../node_modules/react-native-smart-code/ios/RNCodeGenerator.podspec'`

**Comment by rendomnet** [comment]
Thank you, it works now.  "react-native-smart-code" is best solution for me.
Also in podfile all my pods are formated like this` "pod 'RNFS', :path => '../node_modules/react-native-fs'"` with "=>" arrow symbol except "react-native-smart-code".

**Comment by RoJoHub** [comment]
> Thank you, it works now. "react-native-smart-code" is best solution for me.
> Also in podfile all my pods are formated like this` "pod 'RNFS', :path => '../node_modules/react-native-fs'"` with "=>" arrow symbol except "react-native-smart-code".

I have two solution.

## 1.  bump version
Maybe you should bump version of **react-native-fs**

```
IMPORTANT
For RN < 0.57 and/or Gradle < 3 you MUST install react-native-fs at version @2.11.17!

For RN >= 0.57 and/or Gradle >= 3 you MUST install react-native-fs at version @2.13.2!
```

## 2. podfile
Cocoapods maybe is updated.So we should change podfile

```diff
-     pod 'RNFS', :path => '../node_modules/react-native-fs'
+    pod 'RNFS', :path => '../node_modules/react-native-fs/RNFS.podspec'
```
