### ISSUE TITLE
0.60 [!] No podspec found for `react-native-smart-code` in `../node_modules/react-native-smart-code/ios`

### ISSUE THREAD

**Issue by rendomnet** [RoJoHub/react-native-smart-code#24]
When I use 0.60+ RN autolinking gives this error.
[!] No podspec found for `react-native-smart-code` in `../node_modules/react-native-smart-code/ios`

after I used this command: 
pod install --repo-update

**Comment by loveaurellu** [comment]
Podspec name should be `RNCodeGenerator` and not `react-native-smart-code`
https://github.com/RoJoHub/react-native-smart-code/blob/19fd7c1f3db57ab9465a9aaf8030a950e1db0948/ios/RNCodeGenerator.podspec#L6

**Comment by RoJoHub** [comment]
thank you very much!
