### ISSUE TITLE
There are multiple dependencies with different sources for `react-native-smart-code` in `Podfile

### ISSUE THREAD

**Issue by hkar19** [RoJoHub/react-native-smart-code#25]
I have problem on doing `pod install` or `pod update`

this is my error
```
[!] There are multiple dependencies with different sources for `react-native-smart-code` in `Podfile`:

- react-native-smart-code (from `../node_modules/react-native-smart-code/ios`)
- react-native-smart-code (from `../node_modules/react-native-smart-code/ios/RNCodeGenerator.podspec`)
```

how do i fix this error as apparently there is collision inside the same folder?

btw i have this error after upgrading my RN from 0.60 to 0.63

**Comment by mic7010** [comment]
I am on 0.63. In order to get this work I removed the reference in the podfile and copied the node_modules/react-native-smart-code/ios/RNCodeGenerator.podspec to node_modules/react-native-smart-code/ios/react-native-smart-code.podspec. This of course is not a permanent solution. Can the author fix this?

**Comment by hkar19** [comment]
> I am on 0.63. In order to get this work I removed the reference in the podfile and copied the node_modules/react-native-smart-code/ios/RNCodeGenerator.podspec to node_modules/react-native-smart-code/ios/react-native-smart-code.podspec. This of course is not a permanent solution. Can the author fix this?

My build succeeded after i did just that. Maybe there is different way RN fetching podscpec that i dont undestand.

But maybe later this needs to be fixed.

**Comment by RoJoHub** [comment]
please don't use `react-native link react-native-smart-code` if you project is 0.60+.
@hkar19 @mic7010

**Comment by hkar19** [comment]
I was upgrading my RN from 0.60.x.

Everything was just fine until i upgraded. Removing the pod in Podfile does not work as it will give another error.

**Comment by RoJoHub** [comment]
Here you need to open the iOS project and delete react-native-smart-code (not in the pod directory)

**Comment by mic7010** [comment]
In my case I never linked. I used the auto linking. react-native-smart-code does not exist except in the pod directory.

**Comment by RoJoHub** [comment]
> In my case I never linked. I used the auto linking. react-native-smart-code does not exist except in the pod directory.

There should be no problem with the component, but there is a problem with your integration method.
Because I created a new project to integrate and found that everything is normal

**Comment by hkar19** [comment]
> Here you need to open the iOS project and delete react-native-smart-code (not in the pod directory)

what `react-native-smart-code` here are you referring to?

**Comment by RoJoHub** [comment]
hi guys . now is ok

**Comment by RoJoHub** [comment]
please use 1.1.0

**Comment by hkar19** [comment]
did you do something regarding this issue?
